# Server configuration
server:
  port: 8080

# H2 database configuration (optional for testing)
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
